sudo: required
services: 
   - docker

before_install:
   - docker build -t shreyanshgoyal/docker-react -f Dockerfile.dev .

script:
   - docker run shreyanshgoyal/docker-react npm run test -- --coverage